POST http://localhost:7500/simulateScenario HTTP/1.1
content-type: application/json

{
  "items": [
    {
      "itemId": "1",
      "locationId": "e012316ffa0f8435e4817746"
    },
    {
      "itemId": "2",
      "locationId": "e012316ffa0f8435e4817746"
    },
    {
      "itemId": "3",
      "locationId": "a0df66363cda731d83c4337e"
    },
    {
      "itemId": "4",
      "locationId": "a29f1dc0d962108eb1156a9b"
    },
    {
      "itemId": "5",
      "locationId": "8d9e960a364e135404c9b7fe"
    },
    {
      "itemId": "6",
      "locationId": "7bceb3f610b94c066a895b1d"
    },
    {
      "itemId": "7",
      "locationId": "14afbb7c57f546c67a51d616"
    },
    {
      "itemId": "8",
      "locationId": "dda910610fb3dec14961f3cf"
    },
    {
      "itemId": "9",
      "locationId": "dda910610fb3dec14961f3cf"
    },
    {
      "itemId": "10",
      "locationId": "41121882bc55976fc47dcd6b"
    },
    {
      "itemId": "11",
      "locationId": "1f4a92e8aff6d0de5b91649b"
    },
    {
      "itemId": "12",
      "locationId": "77d8df0875ecd02b76758871"
    },
    {
      "itemId": "13",
      "locationId": "b0c5649c5fb80660e4f01957"
    },
    {
      "itemId": "14",
      "locationId": "beef05c105c92575ae9fb6e7"
    },
    {
      "itemId": "15",
      "locationId": "bccd1a591d89fa5881a66edb"
    },
    {
      "itemId": "16",
      "locationId": "0f262fd76e162f7b81b30521"
    },
    {
      "itemId": "17",
      "locationId": "0f262fd76e162f7b81b30521"
    },
    {
      "itemId": "18",
      "locationId": "a0ce6817d8edc912d111ef48"
    },
    {
      "itemId": "19",
      "locationId": "d406c37e36d74c2a7f43005e"
    },
    {
      "itemId": "20",
      "locationId": "88cc47a16ad34cf7ff0c4ffa"
    },
    {
      "itemId": "21",
      "locationId": "8450b8e482c27e6b0b76b39c"
    },
    {
      "itemId": "22",
      "locationId": "c1337f1e9bfa6b7ff4ca5436"
    },
    {
      "itemId": "23",
      "locationId": "95696d242ce839fb807a37cf"
    },
    {
      "itemId": "24",
      "locationId": "4b578c1dc8e176845b3817d0"
    },
    {
      "itemId": "25",
      "locationId": "6ed32f7c0aeecb93e2dca387"
    },
    {
      "itemId": "26",
      "locationId": "acd497ceb8c06d4e51cad301"
    },
    {
      "itemId": "27",
      "locationId": "6a0c3c5a959486b1eaa42f02"
    },
    {
      "itemId": "28",
      "locationId": "46f83a86f5227fe32be27fd8"
    },
    {
      "itemId": "29",
      "locationId": "46f83a86f5227fe32be27fd8"
    },
    {
      "itemId": "30",
      "locationId": "46f83a86f5227fe32be27fd8"
    },
    {
      "itemId": "31",
      "locationId": "faa714630a72cb7424653daf"
    },
    {
      "itemId": "32",
      "locationId": "40ba3d70e2816f3bc35426c1"
    },
    {
      "itemId": "33",
      "locationId": "7cd7bf8e3c04a4bf78343fe3"
    },
    {
      "itemId": "34",
      "locationId": "c1575f9a5f3f556b41786734"
    },
    {
      "itemId": "35",
      "locationId": "5a5e7196ee560035492931f5"
    },
    {
      "itemId": "36",
      "locationId": "324af77ea94238ce9891c578"
    },
    {
      "itemId": "37",
      "locationId": "019899f48d82e0607d27aed2"
    },
    {
      "itemId": "38",
      "locationId": "adeaad87a86b519e8a7624c2"
    },
    {
      "itemId": "39",
      "locationId": "27cbe7ef6915f3b3415031b6"
    },
    {
      "itemId": "40",
      "locationId": "3bfe60393be265989211ec93"
    },
    {
      "itemId": "41",
      "locationId": "3bfe60393be265989211ec93"
    },
    {
      "itemId": "42",
      "locationId": "4a88d4b6c829df165a52d1d4"
    },
    {
      "itemId": "43",
      "locationId": "f5c482d5d54c464c59619026"
    },
    {
      "itemId": "44",
      "locationId": "3e8cd8bb4e8022e78082e343"
    },
    {
      "itemId": "45",
      "locationId": "79e232bd0a1b1e8c83f81435"
    },
    {
      "itemId": "46",
      "locationId": "6243ba6dfa268253ef0385e8"
    },
    {
      "itemId": "47",
      "locationId": "daeaccb32702920050d867b0"
    },
    {
      "itemId": "48",
      "locationId": "3c3086172d34676bc2ff6e2f"
    },
    {
      "itemId": "49",
      "locationId": "afa451f9a6167f02887000c5"
    },
    {
      "itemId": "50",
      "locationId": "ed49fe6c9cabc362d805e49e"
    },
    {
      "itemId": "51",
      "locationId": "58a50ddf91095c052e330fd6"
    },
    {
      "itemId": "52",
      "locationId": "e28eaef36026c5bf9e6a0a8b"
    },
    {
      "itemId": "53",
      "locationId": "6af6e4c4ad777945bd0c9e3b"
    },
    {
      "itemId": "54",
      "locationId": "1f38eec86df28dfa69bde16c"
    },
    {
      "itemId": "55",
      "locationId": "1f38eec86df28dfa69bde16c"
    },
    {
      "itemId": "56",
      "locationId": "1f38eec86df28dfa69bde16c"
    },
    {
      "itemId": "57",
      "locationId": "1f38eec86df28dfa69bde16c"
    },
    {
      "itemId": "58",
      "locationId": "7b93f4dcd9bc3808160f96f7"
    },
    {
      "itemId": "59",
      "locationId": "fb041ab29eb2fe198ab5ff36"
    }
  ],
  "trucks": [
    {
      "items": [
        "14",
        "36",
        "24",
        "51",
        "28",
        "29",
        "30",
        "12",
        "34",
        "31",
        "5",
        "32",
        "25",
        "4",
        "33",
        "44"
      ],
      "route": [
        {
          "destination": "beef05c105c92575ae9fb6e7",
          "duration": 1224,
          "origin": "ce6feed06bc1a9e5aff95f04"
        },
        {
          "destination": "324af77ea94238ce9891c578",
          "duration": 799,
          "origin": "beef05c105c92575ae9fb6e7"
        },
        {
          "destination": "4b578c1dc8e176845b3817d0",
          "duration": 208,
          "origin": "324af77ea94238ce9891c578"
        },
        {
          "destination": "58a50ddf91095c052e330fd6",
          "duration": 159,
          "origin": "4b578c1dc8e176845b3817d0"
        },
        {
          "destination": "46f83a86f5227fe32be27fd8",
          "duration": 219,
          "origin": "58a50ddf91095c052e330fd6"
        },
        {
          "destination": "77d8df0875ecd02b76758871",
          "duration": 103,
          "origin": "46f83a86f5227fe32be27fd8"
        },
        {
          "destination": "c1575f9a5f3f556b41786734",
          "duration": 600,
          "origin": "77d8df0875ecd02b76758871"
        },
        {
          "destination": "faa714630a72cb7424653daf",
          "duration": 54,
          "origin": "c1575f9a5f3f556b41786734"
        },
        {
          "destination": "8d9e960a364e135404c9b7fe",
          "duration": 416,
          "origin": "faa714630a72cb7424653daf"
        },
        {
          "destination": "40ba3d70e2816f3bc35426c1",
          "duration": 187,
          "origin": "8d9e960a364e135404c9b7fe"
        },
        {
          "destination": "6ed32f7c0aeecb93e2dca387",
          "duration": 99,
          "origin": "40ba3d70e2816f3bc35426c1"
        },
        {
          "destination": "a29f1dc0d962108eb1156a9b",
          "duration": 315,
          "origin": "6ed32f7c0aeecb93e2dca387"
        },
        {
          "destination": "7cd7bf8e3c04a4bf78343fe3",
          "duration": 102,
          "origin": "a29f1dc0d962108eb1156a9b"
        },
        {
          "destination": "3e8cd8bb4e8022e78082e343",
          "duration": 212,
          "origin": "7cd7bf8e3c04a4bf78343fe3"
        },
        {
          "destination": "ce6feed06bc1a9e5aff95f04",
          "duration": 809,
          "origin": "3e8cd8bb4e8022e78082e343"
        }
      ],
      "truck_id": "5534TPH"
    },
    {
      "items": [
        "1",
        "2",
        "10",
        "8",
        "9",
        "40",
        "41",
        "16",
        "17",
        "13",
        "54",
        "55",
        "56",
        "57",
        "46",
        "50",
        "58",
        "3",
        "19",
        "27",
        "53",
        "18",
        "47",
        "23",
        "59",
        "7",
        "6"
      ],
      "route": [
        {
          "destination": "e012316ffa0f8435e4817746",
          "duration": 327,
          "origin": "ce6feed06bc1a9e5aff95f04"
        },
        {
          "destination": "41121882bc55976fc47dcd6b",
          "duration": 198,
          "origin": "e012316ffa0f8435e4817746"
        },
        {
          "destination": "dda910610fb3dec14961f3cf",
          "duration": 86,
          "origin": "41121882bc55976fc47dcd6b"
        },
        {
          "destination": "3bfe60393be265989211ec93",
          "duration": 302,
          "origin": "dda910610fb3dec14961f3cf"
        },
        {
          "destination": "0f262fd76e162f7b81b30521",
          "duration": 365,
          "origin": "3bfe60393be265989211ec93"
        },
        {
          "destination": "b0c5649c5fb80660e4f01957",
          "duration": 296,
          "origin": "0f262fd76e162f7b81b30521"
        },
        {
          "destination": "1f38eec86df28dfa69bde16c",
          "duration": 240,
          "origin": "b0c5649c5fb80660e4f01957"
        },
        {
          "destination": "6243ba6dfa268253ef0385e8",
          "duration": 359,
          "origin": "1f38eec86df28dfa69bde16c"
        },
        {
          "destination": "ed49fe6c9cabc362d805e49e",
          "duration": 108,
          "origin": "6243ba6dfa268253ef0385e8"
        },
        {
          "destination": "7b93f4dcd9bc3808160f96f7",
          "duration": 167,
          "origin": "ed49fe6c9cabc362d805e49e"
        },
        {
          "destination": "a0df66363cda731d83c4337e",
          "duration": 131,
          "origin": "7b93f4dcd9bc3808160f96f7"
        },
        {
          "destination": "d406c37e36d74c2a7f43005e",
          "duration": 162,
          "origin": "a0df66363cda731d83c4337e"
        },
        {
          "destination": "6a0c3c5a959486b1eaa42f02",
          "duration": 237,
          "origin": "d406c37e36d74c2a7f43005e"
        },
        {
          "destination": "6af6e4c4ad777945bd0c9e3b",
          "duration": 99,
          "origin": "6a0c3c5a959486b1eaa42f02"
        },
        {
          "destination": "a0ce6817d8edc912d111ef48",
          "duration": 148,
          "origin": "6af6e4c4ad777945bd0c9e3b"
        },
        {
          "destination": "daeaccb32702920050d867b0",
          "duration": 394,
          "origin": "a0ce6817d8edc912d111ef48"
        },
        {
          "destination": "95696d242ce839fb807a37cf",
          "duration": 393,
          "origin": "daeaccb32702920050d867b0"
        },
        {
          "destination": "fb041ab29eb2fe198ab5ff36",
          "duration": 690,
          "origin": "95696d242ce839fb807a37cf"
        },
        {
          "destination": "14afbb7c57f546c67a51d616",
          "duration": 389,
          "origin": "fb041ab29eb2fe198ab5ff36"
        },
        {
          "destination": "7bceb3f610b94c066a895b1d",
          "duration": 47,
          "origin": "14afbb7c57f546c67a51d616"
        },
        {
          "destination": "ce6feed06bc1a9e5aff95f04",
          "duration": 380,
          "origin": "7bceb3f610b94c066a895b1d"
        }
      ],
      "truck_id": "3953RLD"
    },
    {
      "items": [
        "48",
        "20",
        "43",
        "42"
      ],
      "route": [
        {
          "destination": "3c3086172d34676bc2ff6e2f",
          "duration": 2609,
          "origin": "ce6feed06bc1a9e5aff95f04"
        },
        {
          "destination": "88cc47a16ad34cf7ff0c4ffa",
          "duration": 540,
          "origin": "3c3086172d34676bc2ff6e2f"
        },
        {
          "destination": "f5c482d5d54c464c59619026",
          "duration": 508,
          "origin": "88cc47a16ad34cf7ff0c4ffa"
        },
        {
          "destination": "4a88d4b6c829df165a52d1d4",
          "duration": 1502,
          "origin": "f5c482d5d54c464c59619026"
        },
        {
          "destination": "ce6feed06bc1a9e5aff95f04",
          "duration": 592,
          "origin": "4a88d4b6c829df165a52d1d4"
        }
      ],
      "truck_id": "9593DXM"
    },
    {
      "items": [
        "38"
      ],
      "route": [
        {
          "destination": "adeaad87a86b519e8a7624c2",
          "duration": 3041,
          "origin": "ce6feed06bc1a9e5aff95f04"
        },
        {
          "destination": "ce6feed06bc1a9e5aff95f04",
          "duration": 3082,
          "origin": "adeaad87a86b519e8a7624c2"
        }
      ],
      "truck_id": "6965XLY"
    },
    {
      "items": [
        "39",
        "35",
        "15",
        "22"
      ],
      "route": [
        {
          "destination": "27cbe7ef6915f3b3415031b6",
          "duration": 841,
          "origin": "ce6feed06bc1a9e5aff95f04"
        },
        {
          "destination": "5a5e7196ee560035492931f5",
          "duration": 282,
          "origin": "27cbe7ef6915f3b3415031b6"
        },
        {
          "destination": "bccd1a591d89fa5881a66edb",
          "duration": 266,
          "origin": "5a5e7196ee560035492931f5"
        },
        {
          "destination": "c1337f1e9bfa6b7ff4ca5436",
          "duration": 40,
          "origin": "bccd1a591d89fa5881a66edb"
        },
        {
          "destination": "ce6feed06bc1a9e5aff95f04",
          "duration": 735,
          "origin": "c1337f1e9bfa6b7ff4ca5436"
        }
      ],
      "truck_id": "6270NFM"
    },
    {
      "items": [
        "52",
        "49",
        "21",
        "45",
        "37",
        "11",
        "26"
      ],
      "route": [
        {
          "destination": "e28eaef36026c5bf9e6a0a8b",
          "duration": 1492,
          "origin": "ce6feed06bc1a9e5aff95f04"
        },
        {
          "destination": "afa451f9a6167f02887000c5",
          "duration": 178,
          "origin": "e28eaef36026c5bf9e6a0a8b"
        },
        {
          "destination": "8450b8e482c27e6b0b76b39c",
          "duration": 1551,
          "origin": "afa451f9a6167f02887000c5"
        },
        {
          "destination": "79e232bd0a1b1e8c83f81435",
          "duration": 891,
          "origin": "8450b8e482c27e6b0b76b39c"
        },
        {
          "destination": "019899f48d82e0607d27aed2",
          "duration": 211,
          "origin": "79e232bd0a1b1e8c83f81435"
        },
        {
          "destination": "1f4a92e8aff6d0de5b91649b",
          "duration": 1164,
          "origin": "019899f48d82e0607d27aed2"
        },
        {
          "destination": "acd497ceb8c06d4e51cad301",
          "duration": 14,
          "origin": "1f4a92e8aff6d0de5b91649b"
        },
        {
          "destination": "ce6feed06bc1a9e5aff95f04",
          "duration": 457,
          "origin": "acd497ceb8c06d4e51cad301"
        }
      ],
      "truck_id": "0013DYS"
    }
  ]
}

